credentials:
  usernames:
    user1:
      email: user1@email.com
      name: Usuário 1
      password: '$2b$12$aSOMENTExHASHt6xwM91asr4fyIZVFXvTBoPMjOq7eGoaxJqNQjqSu'
      level: 4
      estado: 'SP'
      empresa: 'EmpresaX'
    admin:
      email: admin@email.com
      name: Admin
      password: '$2b$12$xDPRFxkGkJW8gfCjMFLbOewxzAp1zi9KvNwSPwhQXZbJLwKfSv5iG'
      level: 8
      estado: 'RJ'
      empresa: 'EmpresaY'
    user2:
      email: User2@email.com
      name: Usuario 2
      password: '$2b$12$xDPRFxkGkJW8gfCjMFLbOewxzAp1zi9KvNwSPwhQXZbJLwKfSv5iG'
      level: 2
      estado: 'Pe'
      empresa: 'EmpresaX'
    user3:
      email: User2@email.com
      name: Usuario 2
      password: '$2b$12$xDPRFxkGkJW8gfCjMFLbOewxzAp1zi9KvNwSPwhQXZbJLwKfSv5iG'
      level: 1
      estado: 'RJ'
      empresa: 'EmpresaX'
cookie:
  name: some_cookie_name
  key: some_signature_key
  expiry_days: 30